"""empty message

Revision ID: 334fa8bf41de
Revises: 
Create Date: 2022-10-27 12:07:05.885412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334fa8bf41de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
